version: '2'
services:
    jhipstermongodbsampleapplication-app:
        image: jhipstermongodbsampleapplication
        external_links:
            - jhipstermongodbsampleapplication-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipsterMongodbSampleApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstermongodbsampleapplication-mongodb:
        extends:
            file: mongodb.yml
            service: jhipstermongodbsampleapplication-mongodb
