version: '2'
services:
    jhipstermongodbsampleapplication-mongodb:
        container_name: jhipstermongodbsampleapplication-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/jhipsterMongodbSampleApplication/mongodb/:/data/db/
